# --- builder stage ---
FROM golang:1.24.1-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/migrate ./cmd/migrate/main.go

# --- runtime stage ---
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/migrate /app/migrate
COPY migrations /app/migrations
COPY .env /app/.env
RUN chmod +x /app/migrate
ENTRYPOINT ["/app/migrate"]